### PR TITLE
Command line options for making plots

### PR DESCRIPTION
**Pull request by willettk**
Now the analysis can be run on the command line, so long as the data are included in the repo (and automatically makes plots). Eg:

```
[willettk@x-134-84-134-173 analysis]$ python stacked_plots.py -h
Usage: python stacked_plots.py -c <conference>

Conferences with data:
    2015chile
    2015LGAstrostats
    aas225
[willettk@x-134-84-134-173 analysis]$ python stacked_plots.py -c aas225
                       M         F
Male speaker    0.803797  0.196203
Female speaker  0.767327  0.232673

[2 rows x 2 columns]
                     M         F
Male chair    0.824934  0.175066
Female chair  0.687500  0.312500

[2 rows x 2 columns]
                              M         F
Man asks question 1    0.809339  0.190661
Woman asks question 1  0.818182  0.181818

[2 rows x 2 columns]
[willettk@x-134-84-134-173 analysis]$ 
```

### CODE REVIEW

**Comment by karraki** [comment]
Is it possible to do a local merge of pull requests if I don't have write access to this repo?
If not I can just wait for the pull request to be accepted before doing tests, etc.

**Comment by willettk** [comment]
Hm - I'm not positive. You could clone my fork of the repo and run tests on that, if you want.

**Comment by karraki** [comment]
Looks good!

Can we add a print statement with the name of the conference the code is running on?

**Comment by willettk** [comment]
Added in https://github.com/jradavenport/Gender-in-Astro/pull/5.

**Pull request merged**
